spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.property-naming-strategy: SNAKE_CASE

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true